name = "warp"
main = "src/index.ts"
compatibility_date = "2023-08-23"

[[d1_databases]]
binding = "DATABASE"
database_name = "warpflare"
database_id = "90b9ff24-b873-4719-b9ec-142505658209"

[triggers]
crons = [
    '* * * * *', # every minute
]

